# hello-go-deploy-aws task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-aws

outputs:
- name: coverage-results

run:
  path: ./hello-go-deploy-aws/ci/scripts/unit-tests.sh
