# hello-go-deploy-aws task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-aws

run:
  path: ./hello-go-deploy-aws/ci/scripts/deploy.sh
  # args: [-debug]

