# hello-go-deploy-amazon-ec2 task-readme-github-pages.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: hello-go-deploy-amazon-ec2

outputs:
  - name: hello-go-deploy-amazon-ec2-updated

run:
  path: ./hello-go-deploy-amazon-ec2/ci/scripts/readme-github-pages.sh
  # args: [-debug]
