# hello-go-deploy-aws task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-aws

outputs:
- name: hello-go-deploy-aws-updated

run:
  path: ./hello-go-deploy-aws/ci/scripts/readme-github-pages.sh
